teleop:
  follow:
    type: service
    service_name: /swarm_set_command
    service_request:
      command: 'follow'
    buttons: [0]

  dismiss:
    type: service
    service_name: /swarm_set_command
    service_request:
      command: 'dismiss'
    buttons: [2]

  cover:
    type: service
    service_name: /swarm_set_command
    service_request:
      command: 'cover'
    buttons: [1]